version: '3'
services:
  mongodb:
    image: mongo
    logging:
      driver: none
    networks:
      - demo
    ports:
      - '27017:27017'

  payroll:
    image: node:10
    working_dir: /usr/src/app
    container_name: 'payroll_demo'
    env_file:
      - ./payroll/.env
    depends_on:
      - mongodb
    networks:
      - demo
    ports:
      - '8012:8012'
    volumes:
      - './payroll:/usr/src/app'
      - '/root/.npm'
    command: bash -c "npm run docker:dev"

  mongo-seeding:
    image: node:10
    container_name: mongo_seeding
    volumes:
      - './payroll:/usr/src/app/payroll'
    depends_on:
      - mongodb
    #Here is the command we use to initiate the mongodb seeding
    command: >
      sh -c " npm install -g mongo-seeding-cli
      && cd /usr/src/app/payroll/seed && npm i && seed -u 'mongodb://mongodb:27017/payroll' --drop-database /usr/src/app/payroll/seed/data"
    networks:
      - demo

networks:
  demo:
    driver: bridge
